# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: eshopweb
summary: Dev environment for eShop
description: Dev environment for eShop
templatePath: ./infra/main.bicep
runner: bicep
parameters:
  - id: environmentName
    type: string
    name: Environment Name
    description: Name of the environment
    default: dev
  - id: location
    type: string
    name: Location
    description: Azure region for the environment
    default: eastus2
  - id: eventbus_password
    type: string
    name: Event Bus Password
    description: Password for the event bus
    default: password1234
  - id: postgres_password
    type: string
    name: Postgres Password
    description: Password for the postgres database
    default: password1234
