name: "Build .NET Application"
description: "Build and test a .NET application"

inputs:
  working-directory:
    description: 'The working directory for the build and test'
    required: true
  dotnet-version:
    description: "SDK version (e.g., 6.0.x, 7.0.x, 8.0.x, and 9.0.x)"
    default: 9.0.x
    required: true
  configuration:
    description: 'The build configuration to use (allowed values: Debug, Release)'
    default: 'Debug'
    required: true
  verbosity:
    description: 'The verbosity level to use (allowed values: quiet, minimal, normal, detailed, diagnostic)'
    default: 'minimal'
    required: true

runs:
  using: "composite"
  steps:
    - name: Build Application
      id: build-app
      shell: bash
      run: |
        dotnet build ${{ inputs.working-directory }} \
        --configuration ${{ inputs.configuration }} \
        --no-restore \
        --verbosity ${{ inputs.verbosity }}

    - name: Upload artifacts
      id: upload-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-build
        path: ${{ inputs.working-directory }}/bin/${{ inputs.configuration }}/*.dll