name: "Build .NET Application"
description: "Build .NET Application"

inputs:
  inputs:
      working-directory:
        description: 'The working directory for the build and test'
        type: string
        required: true
      dotnet-version:
        description: "SDK version (e.g., 6.0.x, 7.0.x, 8.0.x, and 9.0.x)"
        type: string
        default: 9.0.x
        required: true
      configuration:
        description: 'The build configuration to use (allowed values: Debug, Release)'
        type: string
        default: 'Debug'
        required: true
      verbosity:
        description: 'The verbosity level to use (allowed values: quiet, minimal, normal, detailed, diagnostic)'
        type: string
        default: 'minimal'
        required: true

runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: ./.github/workflows/composite/setup-dotnet.yml
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        working-directory: ${{ inputs.working-directory }}
        
    - name: Build Application
      run: |
          dotnet build ${{ inputs.working-directory }} \
            --configuration ${{ inputs.configuration }} \
            --no-restore \
            --verbosity ${{ inputs.verbosity }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-build
        path: ${{ inputs.working-directory }}/bin/${{ inputs.configuration }}/*.dll