name: "Release .NET Application"
description: "Release .NET Application"

inputs:
  inputs:
      working-directory:
        description: 'The working directory for the build, test and release'
        type: string
        required: true
      dotnet-version:
        description: "SDK version (e.g., 6.0.x, 7.0.x, 8.0.x, and 9.0.x)"
        type: string
        default: 9.0.x
        required: true
      verbosity:
        description: 'The verbosity level to use (allowed values: quiet, minimal, normal, detailed, diagnostic)'
        type: string
        default: 'minimal'
        required: true

runs:
  using: "composite"
  steps:
    - name: Publish Application
      run: |
          dotnet publish ${{ inputs.working-directory }} \
            --configuration ${{ inputs.configuration }} \
            --no-restore \
            --verbosity ${{ inputs.verbosity }} \
            --output ${{ inputs.working-directory }}/bin/${{ inputs.configuration }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
       name: dotnet-release
       path: ${{ inputs.working-directory }}/bin/${{ inputs.configuration }}/*.dll