name: "Setup .NET + Cache"
description: "Install .NET SDK and restore packages with caching"

inputs:
  dotnet-version:
    description: "SDK version (e.g., 6.0.x, 7.0.x, 8.0.x, and 9.0.x)"
    required: true
  working-directory:
    description: "Path for restore"
    required: false
    default: .

outputs:
  cache-hit:
    description: "True if restore was served from cache"
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
  - name: Setup .NET
    id: setup-dotnet
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: ${{ inputs.dotnet-version }}

  - name: Install and Update .NET Workloads
    id: install-workloads
    shell: bash
    run: |
      echo "Installing .NET workloads..."
      dotnet workload install aspire
      dotnet workload install wasm-tools
      echo "Finished installing .NET workloads."

      echo "Updating .NET workloads..."
      dotnet workload update
      echo "Finished updating .NET workloads."

  - name: Compute restore key
    id: key
    shell: bash
    run: echo "key=$(sha256sum ${{ inputs.working-directory }}/**/*.csproj | sha256sum | cut -d' ' -f1)" >> "$GITHUB_OUTPUT"

  - name: Cache packages
    id: cache
    uses: actions/cache@v4
    with:
      path: ~/.nuget/packages
      key: nuget-${{ runner.os }}-${{ steps.key.outputs.key }}

  - name: Restore
    id: restore
    shell: bash
    run: dotnet restore ${{ inputs.working-directory }}
