name: eShop Continuous Integration

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/dotnet-build-and-unit-tests.yml
    strategy:
      matrix:
        dotnet-version: [8,9]
    with:
      solution: './eShop.Web.slnf'
      test: './eShop.Web.slnf'
      dotnet-version: ${{ matrix.dotnet-version }}
      configuration: 'Debug'
      verbosity: 'minimal'
