name: eShop Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/default.yml
    with:
      solution: '**/*.slnf'
      dotnet-version: '9.0.x'
      configuration: 'Release'
