name: Run Unit Tests for DotNet solutions

on:
  workflow_call:
    inputs:
      solution:
        description: 'The solution file to build'
        type: string
        required: true
      dotnet-version:
        description: 'The .NET version to use'
        type: string
        default: '9.0.x'
        required: true
      configuration:
        description: 'The build configuration to use (allowed values: Debug, Release)'
        type: string
        default: 'Debug'
        required: true
      verbosity:
        description: 'The verbosity level to use (allowed values: quiet, minimal, normal, detailed, diagnostic)'
        type: string
        default: 'minimal'
        required: true

jobs:
  test:
    uses: ./.github/workflows/default.yml
    with:
      solution: ${{ inputs.solution }}
      dotnet-version: ${{ inputs.dotnet-version }}
      configuration: ${{ inputs.configuration }}
      verbosity: ${{ inputs.verbosity }}