name: Unit Tests

on:
  workflow_call:
    inputs:
      solution:
        description: 'The solution file to build'
        type: string
        required: true
      dotnet-version:
        description: 'The .NET version to use'
        type: string
        default: '9.0.x'
        required: true
      configuration:
        description: 'The build configuration to use'
        type: string
        default: 'Debug'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Install workloads
        run: |
            echo "Installing .NET workloads..."
            sudo dotnet workload install aspire
            sudo dotnet workload install wasm-tools
            echo "Finished installing .NET workloads."

      - name: Restore and Install Dependencies
        run: dotnet restore ${{ inputs.solution }}

      - name: Run Unit Tests
        run: dotnet test ${{ inputs.solution }} --configuration ${{ inputs.configuration }} --no-restore --verbosity minimal